// import './globals.css'
// import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='d-flex flex-column min-vh-100'>
          <header className="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a className="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">JR Advisors</a>
            <button className="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            {/* <input className="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search" /> */}
            <div className="flex-row flex-grow-1 navbar-nav">
              <div className='nav-item text-nowrap'>
                <a className="nav-link px-3" href="#">Edit Trades</a>
              </div>
              <div className='nav-item text-nowrap'>
                <a className="nav-link px-3" href="#">Manage Contacts</a>
              </div>
              <div className='nav-item text-nowrap'>
                <a className="nav-link px-3" href="#">Monitor Pipelines</a>
              </div>
              <div className='nav-item text-nowrap'>
                <a className="nav-link px-3" href="#">Manage Cross References</a>
              </div>
              <div className='nav-item flex-grow-1'></div>
              <div className="nav-item text-nowrap">
                <a className="nav-link px-3" href="#">Sign out</a>
              </div>
            </div>
          </header>

          <div className='d-flex flex-grow-1'>

            {children}
            {/* <div className='col-md-3 col-lg-3 bg-white'>Test</div> */}
            {/* <div className='col-md-9 col-lg-9 bg-secondary'>Test</div> */}
          </div>
        </div>
      </body>
    </html>
  )
}
